modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/Knozyy/functionalstorage-creative-limiter/issues"

[[mods]]
modId = "fscreativelimiter"
version = "${file.jarVersion}"
displayName = "Functional Storage: Creative Limiter"
displayURL = "https://github.com/Knozyy/functionalstorage-creative-limiter"
logoFile = "fscreativelimiter.png"
authors = "Knozyy"
description = '''
Lets pack makers list items that Functional Storage's Creative Vending Upgrade won't make infinite.
Config: config/functionalstorage/functionalstorage-creative-limiter.toml
'''

[[mixins]]
config = "fscreativelimiter.mixins.json"

[[dependencies.fscreativelimiter]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.233,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fscreativelimiter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fscreativelimiter]]
modId = "functionalstorage"
type = "required"
versionRange = "[1.21.1-1.5.8,)"
ordering = "AFTER"
side = "BOTH"
